
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmvzymjpjwnmtmvccqxh.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdnp5bWpwandubXRtdmNjcXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDIwNDQsImV4cCI6MjA1OTMxODA0NH0.BpoxfNIB4dnr9k1vc810l0Lpd0fUxT9CBZ0a2R2ZX5I";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
